"""empty message

Revision ID: 0907d8b2a84b
Revises: 9850dd1732ed
Create Date: 2020-05-23 11:58:56.836423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0907d8b2a84b'
down_revision = '9850dd1732ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('qnt_update_quota', sa.Integer(), nullable=False))
    op.drop_column('worker', 'qnt_update_quotation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('qnt_update_quotation', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('worker', 'qnt_update_quota')
    # ### end Alembic commands ###
