"""empty message

Revision ID: 2c54f11eefea
Revises: 0907d8b2a84b
Create Date: 2020-05-23 13:26:29.774578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c54f11eefea'
down_revision = '0907d8b2a84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('provider', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'provider')
    # ### end Alembic commands ###
