"""empty message

Revision ID: 5ea8225d6ae3
Revises: 2c54f11eefea
Create Date: 2020-05-30 09:43:49.639212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ea8225d6ae3'
down_revision = '2c54f11eefea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('balance_infos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('balance', sa.Column('result_infos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('balance', sa.Column('total_assets', sa.Float(), nullable=True))
    op.add_column('balance', sa.Column('total_liabilities', sa.Float(), nullable=True))
    op.drop_column('balance', 'net_debt')
    op.drop_column('balance', 'market_value')
    op.drop_column('balance', 'availability')
    op.drop_column('balance', 'deleted_at')
    op.drop_column('balance', 'gross_debt')
    op.drop_column('balance', 'current_assets')
    op.drop_column('balance', 'company_value')
    op.drop_column('balance', 'assets')
    op.drop_column('balance', 'num_action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('num_action', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('balance', sa.Column('assets', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('balance', sa.Column('company_value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('balance', sa.Column('current_assets', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('balance', sa.Column('gross_debt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('balance', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('balance', sa.Column('availability', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('balance', sa.Column('market_value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('balance', sa.Column('net_debt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('balance', 'total_liabilities')
    op.drop_column('balance', 'total_assets')
    op.drop_column('balance', 'result_infos')
    op.drop_column('balance', 'balance_infos')
    # ### end Alembic commands ###
